### ISSUE TITLE
Multiline chat message

### ISSUE THREAD

**Issue by michiruf** [agaertner/bhm-chat-macros#27]
Hello there,

I like your addon very much, but I don't seem to get how one could possibly write multiline messages. Looking at you code, this feature seems pretty much supported. Could you point that out?

Thanky you,
michiruf

**Comment by agaertner** [comment]
Hello, thanks for getting in touch.

it's in the pre-release. I have not officially released the sequencing support because I want to update the UI a bit.

After you enable pre-releases in BlishHUD it should be visible in the library. If it isn't you can get the pre-release on the [releases page](https://github.com/agaertner/bhm-chat-macros/releases) of this repo and install it manually.

**Comment by michiruf** [comment]
Thank you very much!

Do you have an estimate, when it will be released tho?

**Comment by agaertner** [comment]
A few weeks. I have the proof-logix module on my plate right now. You can already use the pre-release without problems though. It's just that I want to make some UI adjustments and have the user add lines rather than there being predefined input textboxes for each line.

**Comment by michiruf** [comment]
I have tried that out. Seems to work pretty well, but in case you do not mean that by adjusting the ui: the input fields may dynamically increase when the last one is filled. Another option would be to stil stick to a textarea and add a checkbox "text is single line" for previous behaviour.

**Comment by agaertner** [comment]
Resolved with module rework
